// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3O_NoEhwcozvOg4wfmhghfMymer1ybME',
    appId: '1:1048755615973:web:c889b62990c447841c3c0c',
    messagingSenderId: '1048755615973',
    projectId: 'letsgo-373714',
    authDomain: 'letsgo-373714.firebaseapp.com',
    storageBucket: 'letsgo-373714.appspot.com',
    measurementId: 'G-LZRLQV1X9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWn33cFo628sUr_OPKfOzndqXlINjV-0',
    appId: '1:1048755615973:android:8e5bd69889474a801c3c0c',
    messagingSenderId: '1048755615973',
    projectId: 'letsgo-373714',
    storageBucket: 'letsgo-373714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChQV7rrn2BHJqCggQs5KM35YzXZ_qfo0',
    appId: '1:1048755615973:ios:f9c420e0569087ac1c3c0c',
    messagingSenderId: '1048755615973',
    projectId: 'letsgo-373714',
    storageBucket: 'letsgo-373714.appspot.com',
    iosClientId: '1048755615973-a4kgbinjtp72po5d1mh14dv3gahf2dqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCChQV7rrn2BHJqCggQs5KM35YzXZ_qfo0',
    appId: '1:1048755615973:ios:f9c420e0569087ac1c3c0c',
    messagingSenderId: '1048755615973',
    projectId: 'letsgo-373714',
    storageBucket: 'letsgo-373714.appspot.com',
    iosClientId: '1048755615973-a4kgbinjtp72po5d1mh14dv3gahf2dqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsgo',
  );
}
