class Lists {
  static final areasList = [
    'BMS College of Engineering',
    'Around Railway Station',
    'Begur Kopa Road',
    'Doddaballapur Road',
    'Electronic City',
    'Hebbal',
    'Hegade Nagar',
    'Hesaraghatta',
    'Hoskote',
    'Hosur',
    'Hosur Road',
    'Indiranagar',
    'International Airport',
    'Jayanagar',
    'JP Nagar',
    'Kaggalipura',
    'KGA Golf Course',
    'Koramangala',
    'Krishnarajapuram',
    'Kundana',
    'Langford Town',
    'Malleswaram',
    'Marathahalli',
    'MG Road',
    'Minerva Circle',
    'Mysore Road',
    'Palace Grounds',
    'Race Course Road',
    'Rajajinagar',
    'Seshadripuram',
    'Shivaji Nagar',
    'Tumkur Road',
    'Ulsoor Lake',
    'Vasanth Nagar',
    'Whitefield',
    'Yelahanka',
    'Yelahanka Devanhalli Road'
  ];
}
